config/routes.rb
Rails.application.routes.draw do
  resources :beer_items
  resources :beers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/models/beer_item.rb
class BeerItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beer_items_controller.rb
class BeerItemsController < ApplicationController
  before_action :set_beer_item, only: %i[ show edit update destroy ]

  # GET /beer_items or /beer_items.json
  def index
    @beer_items = BeerItem.all
  end

  # GET /beer_items/1 or /beer_items/1.json
  def show
  end

  # GET /beer_items/new
  def new
    @beer_item = BeerItem.new
  end

  # GET /beer_items/1/edit
  def edit
  end

  # POST /beer_items or /beer_items.json
  def create
    @beer_item = BeerItem.new(beer_item_params)

    respond_to do |format|
      if @beer_item.save
        format.html { redirect_to beer_item_url(@beer_item), notice: "Beer item was successfully created." }
        format.json { render :show, status: :created, location: @beer_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_items/1 or /beer_items/1.json
  def update
    respond_to do |format|
      if @beer_item.update(beer_item_params)
        format.html { redirect_to beer_item_url(@beer_item), notice: "Beer item was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_items/1 or /beer_items/1.json
  def destroy
    @beer_item.destroy

    respond_to do |format|
      format.html { redirect_to beer_items_url, notice: "Beer item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_item
      @beer_item = BeerItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beer_item_params
      params.require(:beer_item).permit(:beer_name, :brewery, :description, :ibu)
    end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[ show edit update destroy ]

  # GET /beers or /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1 or /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers or /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully created." }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1 or /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully updated." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1 or /beers/1.json
  def destroy
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url, notice: "Beer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beer_params
      params.require(:beer).permit(:beer_name, :Brewery, :Description, :IBU)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_items_helper.rb
module BeerItemsHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beer_items/_beer_item.html.erb
<div id="<%= dom_id beer_item %>">
  <p>
    <strong>Beer name:</strong>
    <%= beer_item.beer_name %>
  </p>

  <p>
    <strong>Brewery:</strong>
    <%= beer_item.brewery %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= beer_item.description %>
  </p>

  <p>
    <strong>Ibu:</strong>
    <%= beer_item.ibu %>
  </p>

</div>

app/views/beer_items/_form.html.erb
<%= form_with(model: beer_item) do |form| %>
  <% if beer_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_item.errors.count, "error") %> prohibited this beer_item from being saved:</h2>

      <ul>
        <% beer_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :beer_name, style: "display: block" %>
    <%= form.text_field :beer_name %>
  </div>

  <div>
    <%= form.label :brewery, style: "display: block" %>
    <%= form.text_field :brewery %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :ibu, style: "display: block" %>
    <%= form.number_field :ibu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/beer_items/edit.html.erb
<h1>Editing beer item</h1>

<%= render "form", beer_item: @beer_item %>

<br>

<div>
  <%= link_to "Show this beer item", @beer_item %> |
  <%= link_to "Back to beer items", beer_items_path %>
</div>

app/views/beer_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beer items</h1>

<div id="beer_items">
  <% @beer_items.each do |beer_item| %>
    <%= render beer_item %>
    <p>
      <%= link_to "Show this beer item", beer_item %>
    </p>
  <% end %>
</div>

<%= link_to "New beer item", new_beer_item_path %>

app/views/beer_items/new.html.erb
<h1>New beer item</h1>

<%= render "form", beer_item: @beer_item %>

<br>

<div>
  <%= link_to "Back to beer items", beer_items_path %>
</div>

app/views/beer_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beer_item %>

<div>
  <%= link_to "Edit this beer item", edit_beer_item_path(@beer_item) %> |
  <%= link_to "Back to beer items", beer_items_path %>

  <%= button_to "Destroy this beer item", @beer_item, method: :delete %>
</div>

app/views/beers/_beer.html.erb
<div class="main">
<div>
<div id="<%= dom_id beer %>">
</br>
<h4> Beers Added:</h4>
<p>
<strong>Beer name:</strong>
</br>
<%= beer.beer_name %>
</p>
</br>
  <p>
    <strong>Brewery:</strong>
    </br>
    <%= beer.Brewery %>
  </p>
  </br>
  <p>
    <strong>Description:</strong>
    </br>
    <%= beer.Description %>
  </p>
  </br>
  <p>
    <strong>Ibu:</strong>
    </br>
    <%= beer.IBU %>
  </p>
  </br>
</div>
</div>
</div>


<div class="cup-pint1"><div class="cup-pint"></div></div>

<div class="water"></div>

<div class="cup"></div>

app/views/beers/_form.html.erb
<div class="main">
<div class="form">
<h4></h4>
<%= form_with(model: beer) do |form| %>
  <% if beer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :beer_name, style: "display: block" %>
    <%= form.text_field :beer_name %>
  </div>

  <div>
    <%= form.label :Brewery, style: "display: block" %>
    <%= form.text_field :Brewery %>
  </div>

  <div>
    <%= form.label :Description, style: "display: block" %>
    <%= form.text_field :Description %>
  </div>

  <div>
    <%= form.label :IBU, style: "display: block" %>
    <%= form.number_field :IBU %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Edit beer</h1>



<%= render "form", beer: @beer %>

  <%= link_to "Show this beer", @beer %> |

  <%= link_to "Back to beers", beers_path %>

app/views/beers/index.html.erb
<h1>beered.co.jp</h1>
<div id="addButton">
<%= link_to "Add beer", new_beer_path %>
</div>
<div id="beers">
  <% @beers.each do |beer| %>
    <%= render beer %>
    </div>
    <p>
    <%= link_to "Show beer", beer %>
    <div id="newBeerButton">
    </div>
    </p>
  <% end %>

app/views/beers/new.html.erb
<h1>New beer</h1>




<%= render "form", beer: @beer %>
<%= link_to "Back to beers", beers_path %>

app/views/beers/show.html.erb
<p style="color: yellow"><%= notice %></p>

<%= render @beer %>

<div>
  <%= link_to "Edit this beer", edit_beer_path(@beer) %> |
  <%= link_to "Back to beers", beers_path %>

  <%= button_to "Delete beer", @beer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeeredRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>